### ISSUE TITLE
Lay down the initial project stucture

### ISSUE THREAD

**Issue by theodesp** [theodesp/go-twillio#1]
We need to bootstrap the project with a good baseline

**Comment by mstruebing** [comment]
I will create a small boilerplate :+1:

**Comment by mstruebing** [comment]
Argh, I cannot make Pull Requests when the repo is empty.

**Comment by theodesp** [comment]
Don't worry I will push a README today!

**Comment by mstruebing** [comment]
Would be interesting what the repository will be about! :)

**Comment by theodesp** [comment]
A Go client for Twillio similar to go-github. I will need to add more tasks to clarify

**Comment by mstruebing** [comment]
I don't know if I will be able to help with the actual implementation, but if you need help setup-wise I'm happy to help!

**Comment by theodesp** [comment]
First thing I did is to rename it to go-twilio 🥇
